sqlite:
  adapter: sqlite3
  database: ":memory:"
mysql:
  adapter: mysql2
  database: unread_test
  username: root
  password: password
  encoding: utf8
  host: 127.0.0.1
  port: 3306
postgres:
  adapter: postgresql
  database: unread_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432
